apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.service.name }}
spec:
  externalTrafficPolicy: "{{ $.Values.specs.trafficPolicy }}"
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
