app:
  name: vault
  hostname: vault-app

specs:
  replicaCount: 3

image:
  repository: rburch4/vaultapp
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  name: vault-app-node
  type: NodePort
  port: 8080
  protocol: TCP
  nodePort: 32003

env:
  mongourl: bW9uZ29kYjovL3Jvb3Q6cm9vdDIzTGlicmFyeUBtb25nby1ub2RlLXN2YzoyNzAxNy8=
  secret: secret

healthCheck:
  path: "/vault/ping"
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 3
  failureThreshold: 3